### ISSUE TITLE
Unable to install iothub-diagnostic on Windows 10

### ISSUE THREAD

**Issue by albhardy** [Azure/iothub-diagnostics#1]
I use both `npm install iothub-diagnostics --msvs_version=2015` and `npm install iothub-diagnostics --msvs_version=2013` after installing visual studio express 2013. Main issue is on `raw-socket` node-gyp rebuild. Following are some of the errors encountered:

![image](https://cloud.githubusercontent.com/assets/1732018/21414438/67ff95f4-c83a-11e6-80ab-3c5f6fab81b0.png)

![image](https://cloud.githubusercontent.com/assets/1732018/21414428/4d15f396-c83a-11e6-9aef-e96e86009fdb.png)

**Comment by pierreca** [comment]
`winsock2.h` is probably either a part of the Windows SDK or one of the Visual Studio redistributables package.

Here's the redist I have: 
![image](https://cloud.githubusercontent.com/assets/4979572/21467645/113e80fa-c9ab-11e6-831a-c171f82929f8.png)
and the windows SDK:
![image](https://cloud.githubusercontent.com/assets/4979572/21467678/6421fbbc-c9ab-11e6-92e5-fe90c4b3fcb7.png)

Hope that helps, please let us know if any of this fixes it!

**Comment by pierreca** [comment]
I have removed the need for raw-sockets in favor of simpler wrappers around system utilities, the change is in the develop branch and should make it to the next release.

**Comment by albhardy** [comment]
Thanks! I managed to install the develop branch on Windows 10.

**Comment by pierreca** [comment]
@albhardy The new version containing that fix (1.1.3) has been published on npm
