### ISSUE TITLE
Port numbers are incorrect in read me

### ISSUE THREAD

**Issue by markrad** [Azure/iothub-diagnostics#3]
# Context
Not Applicable

# Description of the issue:
Documentation error. Your read me states "If the Https and websockets tests are successful, but the AMQP and MQTT tests fail then you should investigate if the ports for AMQP (5672) and/or MQTT (1833) are blocked."
The port number for MQTT should be **8883** and AMQP should be **5671**.

# Console log of the issue:
Not Applicable

# Code sample exhibiting the issue:
Not Applicable

**Comment by pierreca** [comment]
@markrad thanks for filing this issue, the fix has been checked in. in the future please consider opening  a pull request with the suggested changes :)
